baseURL = "http://femme.casa/"
languageCode = "en-us"
title = "Femme.casa"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/categories/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[params]
    since = 2011
    author = "Marley.Kudiabor"                           # Author's name
    avatar = "/images/me/avatar.jpeg"           # Author's avatar
    subtitle = "Adwoa"         # Subtitle
   
    description = "Soy Yo" # site description
    keywords = "" # site keywords

[params.social]
    GitHub = "kudiaborm"
    Twitter = "cogitoergofemme"
    Email   = "kudiaborm@gmail.com"
    Instagram = "cogitoergofemme"
    Mastodon = "I"

[taxonomies]
  tag = "tags"
  category = "categories"
  section = "sections"